In [1]:
import pandas as pd

In [2]:
data = [
    {'Nombre': 'Ana', 'Edad':25, 'Ciudad':'Madrid'},
    {'Nombre': 'Luis', 'Edad':30, 'Ciudad':'Barcelona'},
    {'Nombre': 'Pedro', 'Edad':22, 'Ciudad':'Valencia'}
]

df = pd.DataFrame(data)
df

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
2  Pedro    22   Valencia

In [17]:
data = {
    'Nombre': ['Ana', 'Luis', 'Pedro','Ana'],
    'Edad': [25,30,22,29],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia','Sevilla']
}
df = pd.DataFrame(data)
df

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
2  Pedro    22   Valencia
3    Ana    29    Sevilla

In [18]:
nombres = df['Nombre']
nombres

0      Ana
1     Luis
2    Pedro
3      Ana
Name: Nombre, dtype: object

In [19]:
df['Salario'] = [30000,40000,25000,32000]
df

  Nombre  Edad     Ciudad  Salario
0    Ana    25     Madrid    30000
1   Luis    30  Barcelona    40000
2  Pedro    22   Valencia    25000
3    Ana    29    Sevilla    32000

In [20]:
df.drop('Salario', axis=1, inplace=True)
df

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
2  Pedro    22   Valencia
3    Ana    29    Sevilla

In [16]:
primera_fila = df.iloc[0]
print(primera_fila, end="\n-------------------------\n")
tercera_fila = df.iloc[2]
print(tercera_fila)

Nombre       Ana
Edad          25
Ciudad    Madrid
Name: 0, dtype: object
-------------------------
Nombre       Pedro
Edad            22
Ciudad    Valencia
Name: 2, dtype: object

In [21]:
df.loc[df['Nombre']=='Ana']

  Nombre  Edad   Ciudad
0    Ana    25   Madrid
3    Ana    29  Sevilla

In [22]:
df.loc[df['Edad'] < 30]

  Nombre  Edad    Ciudad
0    Ana    25    Madrid
2  Pedro    22  Valencia
3    Ana    29   Sevilla

In [23]:
df.sort_values(by='Edad', ascending=False)

  Nombre  Edad     Ciudad
1   Luis    30  Barcelona
3    Ana    29    Sevilla
0    Ana    25     Madrid
2  Pedro    22   Valencia

In [24]:
df['Edad'].mean()

26.5

In [25]:
df['Edad'].max()

30

In [27]:
data_w_None = {
    'Nombre': ['Ana', 'Luis', 'Pedro','Ana'],
    'Edad': [25,30,None,29],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia',None]
}
df_none = pd.DataFrame(data_w_None)
df_none

  Nombre  Edad     Ciudad
0    Ana  25.0     Madrid
1   Luis  30.0  Barcelona
2  Pedro   NaN   Valencia
3    Ana  29.0       None

In [30]:
df_without_none = df_none.dropna()
df_without_none

  Nombre  Edad     Ciudad
0    Ana  25.0     Madrid
1   Luis  30.0  Barcelona

In [33]:
df_none.fillna(value={'Edad':20, 'Ciudad':'Lima'})

  Nombre  Edad     Ciudad
0    Ana  25.0     Madrid
1   Luis  30.0  Barcelona
2  Pedro  20.0   Valencia
3    Ana  29.0       Lima