In [1]:
import pandas as pd

In [6]:
data = {
    'Producto': ['Manzanas', 'Naranjas', 'Plátanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90]
}

df = pd.DataFrame(data)

df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Plátanos      60
3      Uvas     120
4     Peras      90

In [3]:
def descuento(x):
    return x * 0.85

In [4]:
df['Precio_Descuento'] = df['Precio'].apply(descuento)
print(df)

   Producto  Precio  Precio_Descuento
0  Manzanas     100              85.0
1  Naranjas      80              68.0
2  Plátanos      60              51.0
3      Uvas     120             102.0
4     Peras      90              76.5

In [5]:
df['Producto'] = df['Producto'].apply(lambda x: x.upper())
df

   Producto  Precio  Precio_Descuento
0  MANZANAS     100              85.0
1  NARANJAS      80              68.0
2  PLÁTANOS      60              51.0
3      UVAS     120             102.0
4     PERAS      90              76.5

In [ ]:
# Se volvio a cargar el dataframe original
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Plátanos      60
3      Uvas     120
4     Peras      90

In [8]:
df['Producto'] = df['Producto'].map({'Manzanas': 'Apples', 'Naranjas': 'Oranges'})
df

  Producto  Precio
0   Apples     100
1  Oranges      80
2      NaN      60
3      NaN     120
4      NaN      90

In [9]:
df = pd.DataFrame(data)
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Plátanos      60
3      Uvas     120
4     Peras      90

In [10]:
df = df.applymap(lambda x: x.lower() if type(x) == str else x)
df

C:\Users\nieto\AppData\Local\Temp\ipykernel_47648\1270923860.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if type(x) == str else x)

   Producto  Precio
0  manzanas     100
1  naranjas      80
2  plátanos      60
3      uvas     120
4     peras      90

In [ ]:
df['Descuento'] = [10, 15, 10, 20, 5]
df

   Producto  Precio  Descuento
0  manzanas     100         10
1  naranjas      80         15
2  plátanos      60         10
3      uvas     120         20
4     peras      90          5

In [13]:
df['Precio_Final'] = df.apply(lambda row: row['Precio'] * (100 - row['Descuento']) / 100, axis=1)
df

   Producto  Precio  Descuento  Precio_Final
0  manzanas     100         10          90.0
1  naranjas      80         15          68.0
2  plátanos      60         10          54.0
3      uvas     120         20          96.0
4     peras      90          5          85.5

In [14]:
data = {
    'Producto': ['Manzanas', 'Naranjas', 'Plátanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90]
}

df = pd.DataFrame(data)
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Plátanos      60
3      Uvas     120
4     Peras      90

In [15]:
mapeo = {'Manzanas': 'Apples', 'Naranjas': 'Oranges'}

df['Producto'] = df['Producto'].map(lambda x: mapeo.get(x, x))
df

   Producto  Precio
0    Apples     100
1   Oranges      80
2  Plátanos      60
3      Uvas     120
4     Peras      90