In [1]:
import pandas as pd

In [2]:
data = {
    'Producto': ['Manzanas', 'Naranjas', 'Plátanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90],
    'Stock': [30, 50, 20, 60, 40]
}

df = pd.DataFrame(data)
df

   Producto  Precio  Stock
0  Manzanas     100     30
1  Naranjas      80     50
2  Plátanos      60     20
3      Uvas     120     60
4     Peras      90     40

In [3]:
suma_precios = df['Precio'].sum()
print("Suma de precios:", suma_precios)

Suma de precios: 450

In [4]:
media_precios = df['Precio'].mean()
print("Media de precios:", media_precios)

Media de precios: 90.0

In [5]:
mediana_precios = df['Precio'].median()
print("Mediana de precios:", mediana_precios)

Mediana de precios: 90.0

In [6]:
min_precio = df['Precio'].min()
max_precio = df['Precio'].max()
print("Mínimo precio:", min_precio)
print("Máximo precio:", max_precio)

Mínimo precio: 60
Máximo precio: 120

In [7]:
std_precio = df['Precio'].std()
var_precio = df['Precio'].var()
print("Desviación estándar de precios:", std_precio)
print("Varianza de precios:", var_precio)

Desviación estándar de precios: 22.360679774997898
Varianza de precios: 500.0

In [8]:
resumen_precios = df['Precio'].describe()
resumen_precios

count      5.00000
mean      90.00000
std       22.36068
min       60.00000
25%       80.00000
50%       90.00000
75%      100.00000
max      120.00000
Name: Precio, dtype: float64

In [9]:
cumsum_precios = df['Precio'].cumsum()
print(cumsum_precios)
df["cum_sum_precios"] = cumsum_precios
df

0    100
1    180
2    240
3    360
4    450
Name: Precio, dtype: int64

   Producto  Precio  Stock  cum_sum_precios
0  Manzanas     100     30              100
1  Naranjas      80     50              180
2  Plátanos      60     20              240
3      Uvas     120     60              360
4     Peras      90     40              450

In [10]:
cumprod_precios = df['Precio'].cumprod()
print(cumprod_precios)
df["cum_prod_precios"] = cumprod_precios
df

0           100
1          8000
2        480000
3      57600000
4    5184000000
Name: Precio, dtype: int64

   Producto  Precio  Stock  cum_sum_precios  cum_prod_precios
0  Manzanas     100     30              100               100
1  Naranjas      80     50              180              8000
2  Plátanos      60     20              240            480000
3      Uvas     120     60              360          57600000
4     Peras      90     40              450        5184000000

In [11]:
diff_precios = df['Precio'].diff()
print(diff_precios)
df["diff_precios"] = diff_precios
df

0     NaN
1   -20.0
2   -20.0
3    60.0
4   -30.0
Name: Precio, dtype: float64

   Producto  Precio  Stock  cum_sum_precios  cum_prod_precios  diff_precios
0  Manzanas     100     30              100               100           NaN
1  Naranjas      80     50              180              8000         -20.0
2  Plátanos      60     20              240            480000         -20.0
3      Uvas     120     60              360          57600000          60.0
4     Peras      90     40              450        5184000000         -30.0

In [12]:
pct_change_precios = df['Precio'].pct_change()
print(pct_change_precios)
df["pct_change_precios"] = pct_change_precios
df

0     NaN
1   -0.20
2   -0.25
3    1.00
4   -0.25
Name: Precio, dtype: float64

,Producto,Precio,Stock,cum_sum_precios,cum_prod_precios,diff_precios,pct_change_precios
0,Manzanas,100,30,100,100,NaN,NaN
1,Naranjas,80,50,180,8000,-20.0,-0.20
2,Plátanos,60,20,240,480000,-20.0,-0.25
3,Uvas,120,60,360,57600000,60.0,1.00
4,Peras,90,40,450,5184000000,-30.0,-0.25