In [1]:
import pandas as pd

In [2]:
data = {
    'Empleado': ['Juan', 'Ana', 'Pedro', 'Luis', 'Maria', 'Ana', 'Pedro', 'Luis', 'Maria'],
    'Departamento': ['Ventas', 'Marketing', 'Ventas', 'IT', 'Marketing', 'IT', 'Ventas', 'Marketing', 'Ventas'],
    'Salario': [50000, 60000, 55000, 58000, 62000, 60000, 55000, 58000, 62000],
    'Años_Experiencia': [5, 7, 6, 8, 9, 7, 6, 8, 9]
}

df = pd.DataFrame(data)
display(df)

  Empleado Departamento  Salario  Años_Experiencia
0     Juan       Ventas    50000                 5
1      Ana    Marketing    60000                 7
2    Pedro       Ventas    55000                 6
3     Luis           IT    58000                 8
4    Maria    Marketing    62000                 9
5      Ana           IT    60000                 7
6    Pedro       Ventas    55000                 6
7     Luis    Marketing    58000                 8
8    Maria       Ventas    62000                 9

In [3]:
df['Departamento'] = df['Departamento'].astype('category')
df['Departamento']

0       Ventas
1    Marketing
2       Ventas
3           IT
4    Marketing
5           IT
6       Ventas
7    Marketing
8       Ventas
Name: Departamento, dtype: category
Categories (3, object): ['IT', 'Marketing', 'Ventas']

In [4]:
df['Departamento'].cat.categories

Index(['IT', 'Marketing', 'Ventas'], dtype='object')

In [5]:
df['Departamento'].cat.codes

0    2
1    1
2    2
3    0
4    1
5    0
6    2
7    1
8    2
dtype: int8

In [6]:
df['Departamento'] = df['Departamento'].cat.reorder_categories(['IT', 'Ventas', 'Marketing'], ordered=True)
df['Departamento']

0       Ventas
1    Marketing
2       Ventas
3           IT
4    Marketing
5           IT
6       Ventas
7    Marketing
8       Ventas
Name: Departamento, dtype: category
Categories (3, object): ['IT' < 'Ventas' < 'Marketing']

In [15]:
df['Departamento'] = df['Departamento'].cat.add_categories(['Recursos Humanos'])

In [17]:
df['Departamento'] = df['Departamento'].cat.remove_categories(['Recursos Humanos'])

In [18]:
df

  Empleado Departamento  Salario  Años_Experiencia
0     Juan       Ventas    50000                 5
1      Ana    Marketing    60000                 7
2    Pedro       Ventas    55000                 6
3     Luis           IT    58000                 8
4    Maria    Marketing    62000                 9
5      Ana           IT    60000                 7
6    Pedro       Ventas    55000                 6
7     Luis    Marketing    58000                 8
8    Maria       Ventas    62000                 9

In [19]:
one_hot = pd.get_dummies(df['Departamento'], prefix='Departamento')
display(one_hot)

   Departamento_IT  Departamento_Ventas  Departamento_Marketing
0            False                 True                   False
1            False                False                    True
2            False                 True                   False
3             True                False                   False
4            False                False                    True
5             True                False                   False
6            False                 True                   False
7            False                False                    True
8            False                 True                   False

In [20]:
agrupacion_categorica = df.groupby('Departamento')['Salario'].sum()
display(agrupacion_categorica)

C:\Users\nieto\AppData\Local\Temp\ipykernel_47324\4120382335.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agrupacion_categorica = df.groupby('Departamento')['Salario'].sum()

Departamento
IT           118000
Ventas       222000
Marketing    180000
Name: Salario, dtype: int64